### ISSUE TITLE
No hangul input possible on KDE 5 / Plasma (Opensuse Leap 42.1)

### ISSUE THREAD

**Issue by michaelof** [choehwanjin/libhangul#13]
Hi, 

installed ibus on my Opensuse Leap 42.1 box, ibus_hangul pkg is version 1.5.0.2.2. I can select "Korean (hangul)", but I only can enter latin keys, no hangul. relase notes are saying that with this version a possibility to "toggle" between hangul and latin was added, but I have no idea how to "toggle". any advice would be great

**Comment by ujuc** [comment]
Kubuntu 16.06. too

**Comment by michaelof** [comment]
SOLVED!

On "https://wiki.archlinux.org/index.php/IBus" I found the solution also for OpenSuse and KDE:

"If IBus does not work in Qt/KDE applications, ensure that the ibus-qt library is installed and define IBus as the default IME in the Qt configuration editor:

$ qtconfig-qt4

In Interface > Default Input Method, select ibus instead of xim."

NOTE: "qtconfig-qt4" on my OpenSuse Leap 42.1 / KDE 5 Plasma is only "qtconfig". On tab "interface" the lowest Dropdown defines the "Default Input Method". 

Setting this to ibus and everything works fine :-)
