### ISSUE TITLE
potential buffer overrun issue in jamo_ext_B_table[] access

### ISSUE THREAD

**Issue by KazuhikoMaekawa** [choehwanjin/libhangul#16]
The following code could bring buffer overrun since jamo_ext_B_table[] definition does not 
have characters between  0xd7c6 and 0xd7cb. Access between these positions should be excluded.

File hangul/hangulctype.c: line 578
-------------------------------------------------------------------
    } else if (c >= 0xd7b0 && c <= 0xd7fb) {
	ret = jamo_ext_B_table[c - 0xd7b0];
-------------------------------------------------------------------

**Comment by choehwanjin** [comment]
Thank you for reporting.

That issue has been fixed already.
https://github.com/choehwanjin/libhangul/commit/3e59c64a985a1355d116319d69973b29d0d8ec66
