### ISSUE TITLE
ubuntu 17.10에서 세벌식 자판 설정 후 한글로 바꿀때 segfault 발생

### ISSUE THREAD

**Issue by tttuuu888** [choehwanjin/libhangul#23]
먼저 이 훌륭한 라이브러리 개발에 정말 감사드립니다.

우분투 16.04에서는 문제가 없었는데, 17.10에서 문제가 발생하네요.
한글 자판을 세벌식 390 으로 설정하고 로그인 후 자판을 한글로 바꾸면 segfault가 발생합니다.
/dev/kmsg의 에러 메세지는 아래와 같습니다.

6,851,5404316732,-;ibus-engine-han[21793]: segfault at 1 ip 00007f357b9c2d7f sp 00007ffeb5267100 error 4 in libhangul.so.1.0.0[7f357b9b9000+1f000]

자판이 두벌식표준으로 설정된 상태에서 로그인 후 한글 설정은 세벌식으로 바꾸면 동작은 하는 상황입니다.

ubuntu 17.10, ibus-hangul 1.5.0 버전에서 위 에러 발생했습니다.

감사합니다.

**Comment by tttuuu888** [comment]
libhangul-0.1.0  버전을 직접 빌드 후 install 하니 정상 동작합니다.
libhangul 라이브러리 자체의 문제가 아니라 우분투를 새로 설정하는 과정에서 뭔가 꼬인것이 아닌가 생각됩니다.
감사합니다.

**Comment by ujuc** [comment]
@tttuuu888 해당 내용으로 https://launchpad.net/ubuntu/+source/ibus-hangul/+bugs 여기에다가 버그 등록을 해주실 수 있을까요?

**Comment by tttuuu888** [comment]
혹시 몰라서 virtualbox에 우분투 17.10을 깔고 다시 테스트 해 본 결과, segfault 재현에 성공하여 내용 덧붙입니다.
아래와 같이 해당 이슈 재현가능했습니다.

1. 우분투 17.10 한글 언어로 설치
2. 최초 ibus-hangul은 정상 동작
3. ppa:createsc/3beol 추가
4. sudo apt update && sudo apt upgrade
5. 해당 이슈 발생

@ujuc 
일단 최초 ibus-hangul package 그대로 사용하면 문제없는걸로 보입니다.

**Comment by cogniti** [comment]
3beol 님의 패치가 적용된 libhangul 이 사용되었나 보군요. 3beol 님께 버그 리포팅하세요
