### ISSUE TITLE
hangul_init()과 hangul_fini()를 사용할 수 없어 보입니다.

### ISSUE THREAD

**Issue by onting** [choehwanjin/libhangul#26]
제 코드에 hangul_init()과 hangul_fini()를 포함한 코드를 작성했는데 컴파일을 하는데  이 두 함수가 implicit declartion이라는 warning이 뜨네요.
libhangul-dev를 설치해 ubuntu에서 개발중입니다.
 정상적으로 이 함수들을 사용할 수 있는게 맞나요?

**Comment by cogniti** [comment]
hangul.h 파일을 인클루드 하셨나요?

**Comment by onting** [comment]
네 인클루드 했지만 경고문이 뜹니다.

**Comment by changwoo** [comment]
릴리스된 1.0.1 버전에 없는 함수입니다. :)

**Comment by onting** [comment]
버전 업그레이드 해서 해결했습니다.
감사합니다
